apiVersion: apps/v1
kind: Deployment
metadata:
  name: platforms-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: platformsservice
  template:
    metadata:
      labels:
        app: platformsservice
    spec:
      containers:
        - name: platformsservice
          image: veaberji/platformservice:latest
